### ISSUE TITLE
Publish to sonatype

### ISSUE THREAD

**Issue by schmitch** [zy4/akka-ipp#6]
Actually we should solve (#1, #2, #3, #4, #5) and then we can actually add http://www.scala-sbt.org/release/docs/Using-Sonatype.html and do our first sonatype publish.

@zy4 can you please register at https://issues.sonatype.org/secure/Signup!default.jspa and tell me your username than I can give you permissions to deploy to `de.envisia.ipp` groupId

**Comment by zy4** [comment]
zinnamon
